/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-05-29 16:25:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class addGroupTask_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/DBConnection.jsp", Long.valueOf(1747368162000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Connection conn = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/task_manager", "root", "");
    } catch (Exception e) {
        out.println("Connection failed: " + e.getMessage());
    }

      out.write('\n');
      out.write('\n');

    String username = (String) session.getAttribute("username");
    Integer userID = (Integer) session.getAttribute("userID");

    if (username == null || userID == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    String message = "";
    PreparedStatement stmt = null;
    PreparedStatement statusStmt = null;
    ResultSet rsGroups = null;
    ResultSet rsStatus = null;

    try {
        if ("POST".equalsIgnoreCase(request.getMethod())) {
            try {
                String subject = request.getParameter("subject");
                String description = request.getParameter("description");
                int groupId = Integer.parseInt(request.getParameter("group_id"));
                int statusId = Integer.parseInt(request.getParameter("status_id"));
                String startDate = request.getParameter("start_date");
                String dueDate = request.getParameter("due_date");
                String maxMemberStr = request.getParameter("max_member");

                int maxMember = 5;
                if (maxMemberStr != null && !maxMemberStr.trim().isEmpty()) {
                    try {
                        maxMember = Integer.parseInt(maxMemberStr);
                    } catch (NumberFormatException e) {
                        maxMember = 5; // default
                    }
                }

                // Cek apakah user adalah leader grup
                String roleCheckSql = "SELECT Role FROM group_members WHERE User_ID = ? AND Group_ID = ?";
                PreparedStatement roleStmt = conn.prepareStatement(roleCheckSql);
                roleStmt.setInt(1, userID);
                roleStmt.setInt(2, groupId);
                ResultSet roleRs = roleStmt.executeQuery();

                if (roleRs.next()) {
                    String role = roleRs.getString("Role");
                    if (!"Leader".equalsIgnoreCase(role)) {
                        message = "Only group leaders can add tasks.";
                    } else {
                        String sqlInsert = "INSERT INTO tasks_group (Subject, Description, Status_ID, Start_Date, Due_Date, Group_ID, User_ID, Max_Members) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                        stmt = conn.prepareStatement(sqlInsert);
                        stmt.setString(1, subject);
                        stmt.setString(2, description);
                        stmt.setInt(3, statusId);
                        stmt.setString(4, startDate);
                        stmt.setString(5, dueDate);
                        stmt.setInt(6, groupId);
                        stmt.setInt(7, userID);
                        stmt.setInt(8, maxMember);

                        int result = stmt.executeUpdate();
                        if (result > 0) {
                            message = "Group task added successfully.";
                        } else {
                            message = "Failed to add group task.";
                        }
                    }
                } else {
                    message = "You are not a member of the selected group.";
                }
                roleRs.close();
                roleStmt.close();
            } catch (NumberFormatException e) {
                message = "Please select a valid group and status, and fill out all fields.";
            }
        }

        // Ambil daftar grup user
        String sqlGroups = "SELECT g.Group_ID, g.Group_Name FROM `groups` g JOIN group_members gm ON g.Group_ID = gm.Group_ID WHERE gm.User_ID = ?";
        stmt = conn.prepareStatement(sqlGroups);
        stmt.setInt(1, userID);
        rsGroups = stmt.executeQuery();

        // Ambil daftar status
        String sqlStatus = "SELECT Status_ID, Name FROM status";
        statusStmt = conn.prepareStatement(sqlStatus);
        rsStatus = statusStmt.executeQuery();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <title>Add Group Task</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\" />\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: 'Outfit', sans-serif;\n");
      out.write("            background-color: #080614;\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            position: relative;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Subtle Blueprint Tech Grid Background */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\";\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background-image: \n");
      out.write("                radial-gradient(rgba(255, 255, 255, 0.015) 1.5px, transparent 1.5px),\n");
      out.write("                linear-gradient(rgba(139, 92, 246, 0.008) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(139, 92, 246, 0.008) 1px, transparent 1px);\n");
      out.write("            background-size: 24px 24px, 48px 48px, 48px 48px;\n");
      out.write("            z-index: 1;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animated Glowing Orbs Background */\n");
      out.write("        .bg-glow {\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            z-index: 0;\n");
      out.write("            overflow: hidden;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1, .glow-2, .glow-3 {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(140px);\n");
      out.write("            opacity: 0.15;\n");
      out.write("            animation: float 25s infinite alternate ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1 {\n");
      out.write("            top: -10%;\n");
      out.write("            left: -10%;\n");
      out.write("            width: 45vw;\n");
      out.write("            height: 45vw;\n");
      out.write("            background: radial-gradient(circle, #8b5cf6 20%, transparent 70%);\n");
      out.write("            animation-duration: 22s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-2 {\n");
      out.write("            bottom: -15%;\n");
      out.write("            right: -5%;\n");
      out.write("            width: 50vw;\n");
      out.write("            height: 50vw;\n");
      out.write("            background: radial-gradient(circle, #3b82f6 20%, transparent 70%);\n");
      out.write("            animation-duration: 30s;\n");
      out.write("            animation-delay: -7s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-3 {\n");
      out.write("            top: 40%;\n");
      out.write("            left: 30%;\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 35vw;\n");
      out.write("            background: radial-gradient(circle, #ec4899 10%, transparent 75%);\n");
      out.write("            animation-duration: 25s;\n");
      out.write("            animation-delay: -12s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0% { transform: translate(0, 0) scale(1) rotate(0deg); }\n");
      out.write("            50% { transform: translate(4vw, 5vh) scale(1.1) rotate(180deg); }\n");
      out.write("            100% { transform: translate(-2vw, -4vh) scale(0.95) rotate(360deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            z-index: 10;\n");
      out.write("            position: relative;\n");
      out.write("            max-width: 540px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin: 0 0 10px 0;\n");
      out.write("            background: linear-gradient(135deg, #fff 40%, rgba(255, 255, 255, 0.7));\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            display: inline-block;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("            background: #14122b !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 24px !important;\n");
      out.write("            box-shadow: 0 30px 60px rgba(0, 0, 0, 0.6) !important;\n");
      out.write("            padding: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-body {\n");
      out.write("            padding: 30px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            color: rgba(255, 255, 255, 0.65);\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control, .form-select {\n");
      out.write("            background: #1c1a38 !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            color: white !important;\n");
      out.write("            padding: 12px 16px !important;\n");
      out.write("            font-size: 15px !important;\n");
      out.write("            transition: all 0.3s ease !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus, .form-select:focus {\n");
      out.write("            background: #252248 !important;\n");
      out.write("            border-color: #a78bfa !important;\n");
      out.write("            outline: none !important;\n");
      out.write("            box-shadow: 0 0 15px rgba(167, 139, 250, 0.25) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control::placeholder {\n");
      out.write("            color: rgba(255, 255, 255, 0.3) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-select option {\n");
      out.write("            background: #0e0c20;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(135deg, #8b5cf6, #6366f1) !important;\n");
      out.write("            border: none !important;\n");
      out.write("            font-weight: 700 !important;\n");
      out.write("            font-size: 15px !important;\n");
      out.write("            padding: 14px 20px !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            box-shadow: 0 6px 20px rgba(139, 92, 246, 0.25) !important;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1) !important;\n");
      out.write("            cursor: pointer;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: linear-gradient(135deg, #a78bfa, #818cf8) !important;\n");
      out.write("            transform: translateY(-2px) !important;\n");
      out.write("            box-shadow: 0 8px 25px rgba(139, 92, 246, 0.4) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: rgba(255, 255, 255, 0.05) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            color: white !important;\n");
      out.write("            font-weight: 600 !important;\n");
      out.write("            font-size: 14px !important;\n");
      out.write("            padding: 10px 18px !important;\n");
      out.write("            border-radius: 12px !important;\n");
      out.write("            transition: all 0.3s ease !important;\n");
      out.write("            margin-bottom: 24px !important;\n");
      out.write("            display: inline-flex !important;\n");
      out.write("            align-items: center !important;\n");
      out.write("            gap: 8px !important;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.12) !important;\n");
      out.write("            border-color: rgba(255, 255, 255, 0.15) !important;\n");
      out.write("            transform: translateY(-1px) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Alert Styling */\n");
      out.write("        .alert {\n");
      out.write("            background: rgba(255, 255, 255, 0.02) !important;\n");
      out.write("            backdrop-filter: blur(20px) !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            color: white !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.05) !important;\n");
      out.write("            padding: 16px 20px !important;\n");
      out.write("            z-index: 20;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-success {\n");
      out.write("            border-color: rgba(16, 185, 129, 0.2) !important;\n");
      out.write("            background: rgba(16, 185, 129, 0.05) !important;\n");
      out.write("            color: #34d399 !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-danger {\n");
      out.write("            border-color: rgba(239, 68, 68, 0.2) !important;\n");
      out.write("            background: rgba(239, 68, 68, 0.05) !important;\n");
      out.write("            color: #fca5a5 !important;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Animated Glowing Orbs Background -->\n");
      out.write("    <div class=\"bg-glow\">\n");
      out.write("        <div class=\"glow-1\"></div>\n");
      out.write("        <div class=\"glow-2\"></div>\n");
      out.write("        <div class=\"glow-3\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col\">\n");
      out.write("                <a href=\"index.jsp?page=group\" class=\"btn-secondary\">\n");
      out.write("                    <i class=\"bi bi-arrow-left\"></i> Back to Group Tasks\n");
      out.write("                </a>\n");
      out.write("                <div class=\"d-block mb-3\">\n");
      out.write("                    <h2>Add Group Task</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 if (!message.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"alert ");
      out.print( message.contains("successfully") ? "alert-success" : "alert-danger" );
      out.write(" alert-dismissible fade show\" role=\"alert\">\n");
      out.write("            ");
      out.print( message );
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <form method=\"post\" novalidate>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"subject\" class=\"form-label\">Subject</label>\n");
      out.write("                    <input type=\"text\" id=\"subject\" name=\"subject\" class=\"form-control\" required />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"description\" class=\"form-label\">Description</label>\n");
      out.write("                    <textarea id=\"description\" name=\"description\" rows=\"3\" class=\"form-control\" required></textarea>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"group_id\" class=\"form-label\">Group</label>\n");
      out.write("                    <select id=\"group_id\" name=\"group_id\" class=\"form-select\" required>\n");
      out.write("                        <option value=\"\">Select Group</option>\n");
      out.write("                        ");
 while (rsGroups != null && rsGroups.next()) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( rsGroups.getInt("Group_ID") );
      out.write('"');
      out.write('>');
      out.print( rsGroups.getString("Group_Name") );
      out.write("</option>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"max_member\" class=\"form-label\">Number of Members</label>\n");
      out.write("                    <input type=\"number\" id=\"max_member\" name=\"max_member\" class=\"form-control\" min=\"1\" max=\"100\" value=\"5\" required />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"status_id\" class=\"form-label\">Status</label>\n");
      out.write("                    <select id=\"status_id\" name=\"status_id\" class=\"form-select\" required>\n");
      out.write("                        <option value=\"\">Select Status</option>\n");
      out.write("                        ");
 while (rsStatus != null && rsStatus.next()) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( rsStatus.getInt("Status_ID") );
      out.write('"');
      out.write('>');
      out.print( rsStatus.getString("Name") );
      out.write("</option>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"start_date\" class=\"form-label\">Start Date</label>\n");
      out.write("                    <input type=\"date\" id=\"start_date\" name=\"start_date\" class=\"form-control\" required />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"due_date\" class=\"form-label\">Due Date</label>\n");
      out.write("                    <input type=\"date\" id=\"due_date\" name=\"due_date\" class=\"form-control\" required />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn-primary\">\n");
      out.write("                    <i class=\"bi bi-save\"></i> Add Group Task\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");

    } catch (Exception e) {
        e.printStackTrace();
        out.println("<p style='color:red; text-align:center;'>Error: " + e.getMessage() + "</p>");
    } finally {
        if (rsGroups != null) try { rsGroups.close(); } catch (Exception ignored) {}
        if (rsStatus != null) try { rsStatus.close(); } catch (Exception ignored) {}
        if (statusStmt != null) try { statusStmt.close(); } catch (Exception ignored) {}
        if (stmt != null) try { stmt.close(); } catch (Exception ignored) {}
        if (conn != null) try { conn.close(); } catch (Exception ignored) {}
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
