/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-05-31 04:24:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class addTask_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/glowingTechElements.jsp", Long.valueOf(1780200909726L));
    _jspx_dependants.put("/DBConnection.jsp", Long.valueOf(1747368162000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    Connection conn = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/task_manager", "root", "");
    } catch (Exception e) {
        out.println("Connection failed: " + e.getMessage());
    }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Add Task</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: 'Outfit', sans-serif;\n");
      out.write("            background-color: #080614;\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            position: relative;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Subtle Blueprint Tech Grid Background */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\";\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background-image: \n");
      out.write("                radial-gradient(rgba(255, 255, 255, 0.015) 1.5px, transparent 1.5px),\n");
      out.write("                linear-gradient(rgba(139, 92, 246, 0.008) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(139, 92, 246, 0.008) 1px, transparent 1px);\n");
      out.write("            background-size: 24px 24px, 48px 48px, 48px 48px;\n");
      out.write("            z-index: 1;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animated Glowing Orbs Background */\n");
      out.write("        .bg-glow {\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            z-index: 0;\n");
      out.write("            overflow: hidden;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1, .glow-2, .glow-3 {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(140px);\n");
      out.write("            opacity: 0.15;\n");
      out.write("            animation: float 25s infinite alternate ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1 {\n");
      out.write("            top: -10%;\n");
      out.write("            left: -10%;\n");
      out.write("            width: 45vw;\n");
      out.write("            height: 45vw;\n");
      out.write("            background: radial-gradient(circle, #8b5cf6 20%, transparent 70%);\n");
      out.write("            animation-duration: 22s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-2 {\n");
      out.write("            bottom: -15%;\n");
      out.write("            right: -5%;\n");
      out.write("            width: 50vw;\n");
      out.write("            height: 50vw;\n");
      out.write("            background: radial-gradient(circle, #3b82f6 20%, transparent 70%);\n");
      out.write("            animation-duration: 30s;\n");
      out.write("            animation-delay: -7s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-3 {\n");
      out.write("            top: 40%;\n");
      out.write("            left: 30%;\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 35vw;\n");
      out.write("            background: radial-gradient(circle, #ec4899 10%, transparent 75%);\n");
      out.write("            animation-duration: 25s;\n");
      out.write("            animation-delay: -12s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0% { transform: translate(0, 0) scale(1) rotate(0deg); }\n");
      out.write("            50% { transform: translate(4vw, 5vh) scale(1.1) rotate(180deg); }\n");
      out.write("            100% { transform: translate(-2vw, -4vh) scale(0.95) rotate(360deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            z-index: 10;\n");
      out.write("            position: relative;\n");
      out.write("            max-width: 540px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin: 0 0 10px 0;\n");
      out.write("            background: linear-gradient(135deg, #fff 40%, rgba(255, 255, 255, 0.7));\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            display: inline-block;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("            background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 24px !important;\n");
      out.write("            box-shadow: 0 30px 60px rgba(0, 0, 0, 0.4),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.1) !important;\n");
      out.write("            padding: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-body {\n");
      out.write("            padding: 30px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            color: rgba(255, 255, 255, 0.65);\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control, .form-select {\n");
      out.write("            background: #1c1a38 !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            color: white !important;\n");
      out.write("            padding: 12px 16px !important;\n");
      out.write("            font-size: 15px !important;\n");
      out.write("            transition: all 0.3s ease !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus, .form-select:focus {\n");
      out.write("            background: rgba(37, 34, 72, 0.6) !important;\n");
      out.write("            border-color: #a78bfa !important;\n");
      out.write("            outline: none !important;\n");
      out.write("            box-shadow: 0 0 18px rgba(167, 139, 250, 0.35) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control::placeholder {\n");
      out.write("            color: rgba(255, 255, 255, 0.3) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-select option {\n");
      out.write("            background: #0e0c20;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(135deg, #8b5cf6, #6366f1) !important;\n");
      out.write("            border: none !important;\n");
      out.write("            font-weight: 700 !important;\n");
      out.write("            font-size: 15px !important;\n");
      out.write("            padding: 14px 20px !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            box-shadow: 0 6px 20px rgba(139, 92, 246, 0.25) !important;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1) !important;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: linear-gradient(135deg, #a78bfa, #818cf8) !important;\n");
      out.write("            transform: translateY(-2px) !important;\n");
      out.write("            box-shadow: 0 8px 25px rgba(139, 92, 246, 0.4) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: rgba(255, 255, 255, 0.05) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            color: white !important;\n");
      out.write("            font-weight: 600 !important;\n");
      out.write("            font-size: 14px !important;\n");
      out.write("            padding: 10px 18px !important;\n");
      out.write("            border-radius: 12px !important;\n");
      out.write("            transition: all 0.3s ease !important;\n");
      out.write("            margin-bottom: 24px !important;\n");
      out.write("            display: inline-flex !important;\n");
      out.write("            align-items: center !important;\n");
      out.write("            gap: 8px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.12) !important;\n");
      out.write("            border-color: rgba(255, 255, 255, 0.15) !important;\n");
      out.write("            transform: translateY(-1px) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Solid Contrast Modal Styling */\n");
      out.write("        .modal-content {\n");
      out.write("            background: #14122b !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 24px !important;\n");
      out.write("            box-shadow: 0 30px 60px rgba(0, 0, 0, 0.6) !important;\n");
      out.write("            color: white !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header {\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.06) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-footer {\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.06) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-title {\n");
      out.write("            font-weight: 700 !important;\n");
      out.write("            color: white !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Alert Styling */\n");
      out.write("        .alert {\n");
      out.write("            background: rgba(255, 255, 255, 0.02) !important;\n");
      out.write("            backdrop-filter: blur(20px) !important;\n");
      out.write("            border-radius: 14px !important;\n");
      out.write("            color: white !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.05) !important;\n");
      out.write("            padding: 16px 20px !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-success {\n");
      out.write("            border-color: rgba(16, 185, 129, 0.2) !important;\n");
      out.write("            background: rgba(16, 185, 129, 0.05) !important;\n");
      out.write("            color: #34d399 !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .alert-danger {\n");
      out.write("            border-color: rgba(239, 68, 68, 0.2) !important;\n");
      out.write("            background: rgba(239, 68, 68, 0.05) !important;\n");
      out.write("            color: #fca5a5 !important;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Animated Glowing Orbs Background -->\n");
      out.write("    <div class=\"bg-glow\">\n");
      out.write("        <div class=\"glow-1\"></div>\n");
      out.write("        <div class=\"glow-2\"></div>\n");
      out.write("        <div class=\"glow-3\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Premium 3D Tech & Glass Elements -->\n");
      out.write("    ");
      out.write("<!-- Reusable Futuristic Glassmorphic & 3D Tech Elements Component -->\n");
      out.write("<style>\n");
      out.write("    /* Technical Abstract Animations */\n");
      out.write("    .tech-element-container {\n");
      out.write("        position: absolute;\n");
      out.write("        top: 0;\n");
      out.write("        left: 0;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        pointer-events: none;\n");
      out.write("        overflow: hidden;\n");
      out.write("        z-index: 2;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Floating Drifting Spheres */\n");
      out.write("    .glass-sphere {\n");
      out.write("        position: absolute;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        animation: sphereDrift 20s infinite alternate ease-in-out;\n");
      out.write("        opacity: 0.25;\n");
      out.write("        mix-blend-mode: plus-lighter;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .sphere-1 {\n");
      out.write("        top: 15%;\n");
      out.write("        right: 12%;\n");
      out.write("        width: 160px;\n");
      out.write("        height: 160px;\n");
      out.write("        animation-duration: 22s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sphere-2 {\n");
      out.write("        bottom: 15%;\n");
      out.write("        left: 10%;\n");
      out.write("        width: 200px;\n");
      out.write("        height: 200px;\n");
      out.write("        animation-duration: 28s;\n");
      out.write("        animation-delay: -5s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes sphereDrift {\n");
      out.write("        0% { transform: translate(0, 0) scale(1) rotate(0deg); }\n");
      out.write("        50% { transform: translate(25px, -30px) scale(1.08) rotate(180deg); }\n");
      out.write("        100% { transform: translate(-15px, 20px) scale(0.95) rotate(360deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Tech Rings Spinning in 3D */\n");
      out.write("    .tech-ring-container {\n");
      out.write("        position: absolute;\n");
      out.write("        width: 300px;\n");
      out.write("        height: 300px;\n");
      out.write("        opacity: 0.15;\n");
      out.write("        mix-blend-mode: screen;\n");
      out.write("        perspective: 1000px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .ring-left {\n");
      out.write("        bottom: 8%;\n");
      out.write("        left: 5%;\n");
      out.write("        animation: driftSlow 35s infinite alternate ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .ring-right {\n");
      out.write("        top: 8%;\n");
      out.write("        right: 5%;\n");
      out.write("        animation: driftSlow 30s infinite alternate ease-in-out -10s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes driftSlow {\n");
      out.write("        0% { transform: translate(0,0) rotate(0deg); }\n");
      out.write("        100% { transform: translate(30px, 40px) rotate(15deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .spinning-ring {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        transform-style: preserve-3d;\n");
      out.write("        animation: spinRing 25s infinite linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .spinning-ring-reverse {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        transform-style: preserve-3d;\n");
      out.write("        animation: spinRingRev 18s infinite linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes spinRing {\n");
      out.write("        from { transform: rotateX(65deg) rotateY(20deg) rotateZ(0deg); }\n");
      out.write("        to { transform: rotateX(65deg) rotateY(20deg) rotateZ(360deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes spinRingRev {\n");
      out.write("        from { transform: rotateX(55deg) rotateY(-25deg) rotateZ(360deg); }\n");
      out.write("        to { transform: rotateX(55deg) rotateY(-25deg) rotateZ(0deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Ambient cyber particles */\n");
      out.write("    .ambient-particle {\n");
      out.write("        position: absolute;\n");
      out.write("        background: #a78bfa;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        opacity: 0;\n");
      out.write("        animation: twinkleParticle 4s infinite ease-in-out;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .particle-1 { top: 30%; left: 25%; width: 3px; height: 3px; animation-delay: 0.2s; }\n");
      out.write("    .particle-2 { top: 75%; left: 45%; width: 4px; height: 4px; animation-delay: 1.5s; background: #3b82f6; }\n");
      out.write("    .particle-3 { top: 20%; right: 30%; width: 3px; height: 3px; animation-delay: 2.8s; background: #ec4899; }\n");
      out.write("    .particle-4 { bottom: 30%; right: 20%; width: 4px; height: 4px; animation-delay: 0.9s; }\n");
      out.write("\n");
      out.write("    @keyframes twinkleParticle {\n");
      out.write("        0%, 100% { opacity: 0; transform: translateY(0) scale(0.8); }\n");
      out.write("        50% { opacity: 0.8; transform: translateY(-15px) scale(1.2); filter: drop-shadow(0 0 4px currentColor); }\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div class=\"tech-element-container\">\n");
      out.write("    <!-- Specular radial gradients inside SVGs for realistic 3D look -->\n");
      out.write("    <svg style=\"position: absolute; width: 0; height: 0;\">\n");
      out.write("        <defs>\n");
      out.write("            <radialGradient id=\"3dGlassGrad\" cx=\"35%\" cy=\"35%\" r=\"65%\">\n");
      out.write("                <stop offset=\"0%\" stop-color=\"#c084fc\" stop-opacity=\"0.6\"/>\n");
      out.write("                <stop offset=\"35%\" stop-color=\"#8b5cf6\" stop-opacity=\"0.3\"/>\n");
      out.write("                <stop offset=\"70%\" stop-color=\"#3b82f6\" stop-opacity=\"0.1\"/>\n");
      out.write("                <stop offset=\"95%\" stop-color=\"#080614\" stop-opacity=\"0.4\"/>\n");
      out.write("                <stop offset=\"100%\" stop-color=\"#8b5cf6\" stop-opacity=\"0.7\"/>\n");
      out.write("            </radialGradient>\n");
      out.write("            <linearGradient id=\"ringNeonGrad\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n");
      out.write("                <stop offset=\"0%\" stop-color=\"#a78bfa\"/>\n");
      out.write("                <stop offset=\"50%\" stop-color=\"#6366f1\"/>\n");
      out.write("                <stop offset=\"100%\" stop-color=\"#22d3ee\"/>\n");
      out.write("            </linearGradient>\n");
      out.write("        </defs>\n");
      out.write("    </svg>\n");
      out.write("\n");
      out.write("    <!-- 1. Floating Abstract Glass Spheres -->\n");
      out.write("    <!-- Sphere 1 (Top-Right) -->\n");
      out.write("    <div class=\"glass-sphere sphere-1\">\n");
      out.write("        <svg viewBox=\"0 0 100 100\" width=\"100%\" height=\"100%\">\n");
      out.write("            <circle cx=\"50\" cy=\"50\" r=\"48\" fill=\"url(#3dGlassGrad)\" stroke=\"rgba(255,255,255,0.15)\" stroke-width=\"0.5\"/>\n");
      out.write("            <!--Specularity -->\n");
      out.write("            <ellipse cx=\"38\" cy=\"38\" rx=\"12\" ry=\"6\" transform=\"rotate(-30 38 38)\" fill=\"white\" opacity=\"0.12\"/>\n");
      out.write("        </svg>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Sphere 2 (Bottom-Left) -->\n");
      out.write("    <div class=\"glass-sphere sphere-2\">\n");
      out.write("        <svg viewBox=\"0 0 100 100\" width=\"100%\" height=\"100%\">\n");
      out.write("            <circle cx=\"50\" cy=\"50\" r=\"48\" fill=\"url(#3dGlassGrad)\" stroke=\"rgba(255,255,255,0.15)\" stroke-width=\"0.5\"/>\n");
      out.write("            <ellipse cx=\"38\" cy=\"38\" rx=\"12\" ry=\"6\" transform=\"rotate(-30 38 38)\" fill=\"white\" opacity=\"0.12\"/>\n");
      out.write("        </svg>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 2. Cybernetic Neon Tech Rings (Perspectival spinning) -->\n");
      out.write("    <!-- Ring Left -->\n");
      out.write("    <div class=\"tech-ring-container ring-left\">\n");
      out.write("        <div class=\"spinning-ring\">\n");
      out.write("            <svg viewBox=\"0 0 200 200\" width=\"100%\" height=\"100%\">\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"90\" fill=\"none\" stroke=\"url(#ringNeonGrad)\" stroke-width=\"1.5\" stroke-dasharray=\"8 6\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"76\" fill=\"none\" stroke=\"#22d3ee\" stroke-width=\"0.8\" stroke-opacity=\"0.3\" stroke-dasharray=\"40 10 5 10\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"96\" fill=\"none\" stroke=\"#a78bfa\" stroke-width=\"0.5\" stroke-opacity=\"0.2\"/>\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Ring Right -->\n");
      out.write("    <div class=\"tech-ring-container ring-right\">\n");
      out.write("        <div class=\"spinning-ring-reverse\">\n");
      out.write("            <svg viewBox=\"0 0 200 200\" width=\"100%\" height=\"100%\">\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"90\" fill=\"none\" stroke=\"url(#ringNeonGrad)\" stroke-width=\"1.5\" stroke-dasharray=\"12 8\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"76\" fill=\"none\" stroke=\"#e879f9\" stroke-width=\"0.8\" stroke-opacity=\"0.3\" stroke-dasharray=\"25 15\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"96\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"0.5\" stroke-opacity=\"0.2\"/>\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 3. Twinkling Ambient Cyber Particles -->\n");
      out.write("    <div class=\"ambient-particle particle-1\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-2\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-3\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-4\"></div>\n");
      out.write("</div>\n");
      out.write('\n');

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    String message = "";
    String alertClass = "";
    
    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String newSubject = request.getParameter("subject");
        String newDescription = request.getParameter("description");
        String newStatus = request.getParameter("status");
        String newStartDate = request.getParameter("startDate");
        String newDueDate = request.getParameter("dueDate");

        if (newDescription == null || newDescription.trim().isEmpty() || newSubject == null || newSubject.trim().isEmpty()) {
            message = "Subject and Description cannot be empty!";
            alertClass = "alert-danger";
        } else {
            try {
                // Insert new task into the database
                String insertSql = "INSERT INTO tasks (Subject, Description, Status_id, Start_date, Due_date, User_ID) " +
                                   "VALUES (?, ?, ?, ?, ?, ?)";
                try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                    insertStmt.setString(1, newSubject.trim());
                    insertStmt.setString(2, newDescription.trim());
                    insertStmt.setInt(3, Integer.parseInt(newStatus)); 
                    insertStmt.setDate(4, java.sql.Date.valueOf(newStartDate));
                    insertStmt.setDate(5, java.sql.Date.valueOf(newDueDate));
                    insertStmt.setInt(6, (Integer) session.getAttribute("userID"));

                    int result = insertStmt.executeUpdate();
                    if (result > 0) {
                        message = "Task added successfully!";
                        alertClass = "alert-success";
                    } else {
                        message = "Failed to add task.";
                        alertClass = "alert-danger";
                    }
                }
            } catch (Exception e) {
                message = "Error: " + e.getMessage();
                alertClass = "alert-danger";
            } finally {
                if (conn != null) try { conn.close(); } catch (SQLException ignore) {}
            }
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-4\">\n");
      out.write("    <div class=\"row mb-3\">\n");
      out.write("        <div class=\"col\">\n");
      out.write("            <h2>Add Task</h2>\n");
      out.write("            <a href=\"index.jsp?page=individual\" class=\"btn btn-secondary mb-3\">\n");
      out.write("                <i class=\"bi bi-arrow-left\"></i> Back to Task List\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (!message.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"alert ");
      out.print( alertClass );
      out.write(" alert-dismissible fade show\" role=\"alert\">\n");
      out.write("            ");
      out.print( message );
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <form method=\"POST\" action=\"addTask.jsp\">\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"subject\" class=\"form-label\">Subject</label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"subject\" name=\"subject\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"description\" class=\"form-label\">Description</label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"description\" name=\"description\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"status\" class=\"form-label\">Status</label>\n");
      out.write("                    <select class=\"form-select\" id=\"status\" name=\"status\">\n");
      out.write("                        <option value=\"1\">Pending</option>\n");
      out.write("                        <option value=\"2\">In Progress</option>\n");
      out.write("                        <option value=\"3\">Cancelled</option>\n");
      out.write("                        <option value=\"4\">Completed</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"startDate\" class=\"form-label\">Start Date</label>\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"startDate\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"dueDate\" class=\"form-label\">Due Date</label>\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"dueDate\" name=\"dueDate\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"d-grid gap-2\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                        <i class=\"bi bi-save\"></i> Add Task\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"taskModal\" tabindex=\"-1\" aria-labelledby=\"taskModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title\" id=\"taskModalLabel\">Task Addition Status</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                ");
      out.print( message );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <a href=\"index.jsp?page=individual\" class=\"btn btn-primary\">Back to Task List</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
 if (!message.isEmpty()) { 
      out.write("\n");
      out.write("    <script>\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("            var taskModal = new bootstrap.Modal(document.getElementById('taskModal'), {\n");
      out.write("                keyboard: false\n");
      out.write("            });\n");
      out.write("            taskModal.show();\n");
      out.write("        });\n");
      out.write("    </script>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
