/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-05-31 04:35:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class individualDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/DBConnection.jsp", Long.valueOf(1747368162000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Connection conn = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/task_manager", "root", "");
    } catch (Exception e) {
        out.println("Connection failed: " + e.getMessage());
    }

      out.write('\n');

    Integer userID = (Integer) session.getAttribute("userID");
    if (userID == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    int pending = 0, inProgress = 0, cancelled = 0, completed = 0;
    int totalTasks = 0;

    String filter = request.getParameter("filter");
    String search = request.getParameter("search");
    String sort = request.getParameter("sort");

    String sql = "SELECT t.ID, t.Subject, t.Description, s.Name, t.Start_date, t.Due_date " +
                 "FROM tasks t JOIN status s ON t.Status_id = s.Status_ID " +
                 "WHERE t.User_ID = ? AND t.Group_ID IS NULL";

    if (search != null && !search.isEmpty()) {
        if (filter != null) {
            if (filter.equals("Subject")) {
                sql += " AND t.Subject LIKE ?";
            } else if (filter.equals("Description")) {
                sql += " AND t.Description LIKE ?";
            } else if (filter.equals("Status")) {
                sql += " AND s.Name LIKE ?";
            }
        }
    }

    if (sort != null && !sort.isEmpty()) {
        if (sort.equals("asc")) {
            sql += " ORDER BY t.Due_date ASC";
        } else if (sort.equals("desc")) {
            sql += " ORDER BY t.Due_date DESC";
        }
    } else {
        sql += " ORDER BY t.ID";
    }

    PreparedStatement stmt = null;
    ResultSet rs = null;
    int counter = 1;

    try {
        stmt = conn.prepareStatement(sql);
        stmt.setInt(1, userID);
        if (search != null && !search.isEmpty()) {
            stmt.setString(2, "%" + search + "%");
        }
        rs = stmt.executeQuery();
        while (rs.next()) {
            String statusName = rs.getString(4);
            switch (statusName) {
                case "Pending": pending++; break;
                case "In Progress": inProgress++; break;
                case "Cancel": cancelled++; break;
                case "Completed": completed++; break;
            }
        }
        totalTasks = pending + inProgress + completed;
        rs.close();
        stmt.close();

        stmt = conn.prepareStatement(sql);
        stmt.setInt(1, userID);
        if (search != null && !search.isEmpty()) {
            stmt.setString(2, "%" + search + "%");
        }
        rs = stmt.executeQuery();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Individual Task Dashboard</title>\n");
      out.write("    <style>\n");
      out.write("        .page-title {\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin: 0 0 24px 0;\n");
      out.write("            background: linear-gradient(135deg, #fff 40%, rgba(255, 255, 255, 0.7));\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            display: inline-block;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 2-Column Dashboard Grid Layout */\n");
      out.write("        .dashboard-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 2.3fr 1fr;\n");
      out.write("            gap: 24px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("            align-items: start;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 1024px) {\n");
      out.write("            .dashboard-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dashboard-left {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .dashboard-right {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar Progress Card */\n");
      out.write("        .summary-card {\n");
      out.write("            background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            padding: 24px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.1) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .summary-card h3 {\n");
      out.write("            margin: 0 0 16px 0;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            color: #a5a1c9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-bar {\n");
      out.write("            background-color: #1c1a38;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("            border-radius: 10px;\n");
      out.write("            height: 12px;\n");
      out.write("            width: 100%;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: inset 0 2px 4px rgba(0,0,0,0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-fill {\n");
      out.write("            height: 100%;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            transition: width 0.5s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-desc {\n");
      out.write("            margin-top: 12px;\n");
      out.write("            margin-bottom: 0;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-desc strong {\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Stats Sidebar Grid */\n");
      out.write("        .stats-sidebar-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            gap: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 576px) {\n");
      out.write("            .stats-sidebar-grid {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box {\n");
      out.write("            background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 16px;\n");
      out.write("            text-align: left;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.1) !important;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-icon {\n");
      out.write("            transition: transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            border-color: rgba(167, 139, 250, 0.3) !important;\n");
      out.write("            box-shadow: 0 12px 25px rgba(139, 92, 246, 0.15),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.15) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box:hover .status-icon {\n");
      out.write("            transform: scale(1.18) rotate(15deg);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-icon {\n");
      out.write("            font-size: 20px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            flex-shrink: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box.pending .status-icon {\n");
      out.write("            background: rgba(245, 158, 11, 0.1);\n");
      out.write("            color: #f59e0b;\n");
      out.write("            border: 1px solid rgba(245, 158, 11, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box.in-progress .status-icon {\n");
      out.write("            background: rgba(59, 130, 246, 0.1);\n");
      out.write("            color: #3b82f6;\n");
      out.write("            border: 1px solid rgba(59, 130, 246, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box.cancelled .status-icon {\n");
      out.write("            background: rgba(239, 68, 68, 0.1);\n");
      out.write("            color: #ef4444;\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box.completed .status-icon {\n");
      out.write("            background: rgba(16, 185, 129, 0.1);\n");
      out.write("            color: #10b981;\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-details {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-details h3 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            line-height: 1.1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-details p {\n");
      out.write("            margin: 2px 0 0 0;\n");
      out.write("            font-size: 11px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: rgba(255, 255, 255, 0.4);\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-box.pending h3 { color: #f59e0b; }\n");
      out.write("        .status-box.in-progress h3 { color: #3b82f6; }\n");
      out.write("        .status-box.cancelled h3 { color: #ef4444; }\n");
      out.write("        .status-box.completed h3 { color: #10b981; }\n");
      out.write("\n");
      out.write("        .dashboard-controls {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 16px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            padding: 16px;\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.1) !important;\n");
      out.write("        }\n");
      out.write("        .btn-add {\n");
      out.write("            background: linear-gradient(135deg, #8b5cf6, #6366f1);\n");
      out.write("            color: white !important;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 14px;\n");
      out.write("            padding: 12px 24px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 15px rgba(139, 92, 246, 0.25);\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .btn-add:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 8px 25px rgba(139, 92, 246, 0.4);\n");
      out.write("            background: linear-gradient(135deg, #a78bfa, #818cf8);\n");
      out.write("        }\n");
      out.write("        .search-form {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 12px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .search-form input[type=\"text\"],\n");
      out.write("        .search-form select {\n");
      out.write("            background: #1c1a38;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("            border-radius: 12px;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 16px;\n");
      out.write("            font-family: inherit;\n");
      out.write("            font-size: 14px;\n");
      out.write("            outline: none;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .search-form input[type=\"text\"]::placeholder {\n");
      out.write("            color: rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("        .search-form input[type=\"text\"]:focus,\n");
      out.write("        .search-form select:focus {\n");
      out.write("            background: #252248;\n");
      out.write("            border-color: #a78bfa;\n");
      out.write("            box-shadow: 0 0 12px rgba(167, 139, 250, 0.25);\n");
      out.write("        }\n");
      out.write("        .search-form select option {\n");
      out.write("            background: #0e0c20;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        .btn-search {\n");
      out.write("            background: rgba(255, 255, 255, 0.06);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        .btn-search:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.12);\n");
      out.write("            border-color: rgba(255, 255, 255, 0.2);\n");
      out.write("            transform: translateY(-1px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            margin-top: 1.5rem;\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: separate;\n");
      out.write("            border-spacing: 0;\n");
      out.write("            background: rgba(20, 18, 43, 0.4) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(110%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(110%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.08) !important;\n");
      out.write("        }\n");
      out.write("        th, td {\n");
      out.write("            padding: 16px 20px;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.06);\n");
      out.write("        }\n");
      out.write("        th {\n");
      out.write("            background: #1c1a38;\n");
      out.write("            color: #a5a1c9;\n");
      out.write("            font-weight: 700;\n");
      out.write("            font-size: 13px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("        }\n");
      out.write("        tr {\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        tr:hover td {\n");
      out.write("            background: rgba(255, 255, 255, 0.01);\n");
      out.write("        }\n");
      out.write("        tr:last-child td {\n");
      out.write("            border-bottom: none;\n");
      out.write("        }\n");
      out.write("        td {\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-label {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            text-align: center;\n");
      out.write("            min-width: 90px;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("        .status-label.Pending {\n");
      out.write("            background: rgba(245, 158, 11, 0.1);\n");
      out.write("            color: #f59e0b;\n");
      out.write("            border: 1px solid rgba(245, 158, 11, 0.25);\n");
      out.write("            box-shadow: 0 0 10px rgba(245, 158, 11, 0.1);\n");
      out.write("        }\n");
      out.write("        .status-label.InProgress {\n");
      out.write("            background: rgba(59, 130, 246, 0.1);\n");
      out.write("            color: #3b82f6;\n");
      out.write("            border: 1px solid rgba(59, 130, 246, 0.25);\n");
      out.write("            box-shadow: 0 0 10px rgba(59, 130, 246, 0.1);\n");
      out.write("        }\n");
      out.write("        .status-label.Cancel {\n");
      out.write("            background: rgba(239, 68, 68, 0.1);\n");
      out.write("            color: #ef4444;\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.25);\n");
      out.write("            box-shadow: 0 0 10px rgba(239, 68, 68, 0.1);\n");
      out.write("        }\n");
      out.write("        .status-label.Completed {\n");
      out.write("            background: rgba(16, 185, 129, 0.1);\n");
      out.write("            color: #10b981;\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.25);\n");
      out.write("            box-shadow: 0 0 10px rgba(16, 185, 129, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-action {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 6px 14px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 13px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-right: 8px;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .btn-action.edit {\n");
      out.write("            background: rgba(16, 185, 129, 0.1);\n");
      out.write("            color: #10b981;\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.25);\n");
      out.write("        }\n");
      out.write("        .btn-action.edit:hover {\n");
      out.write("            background: #10b981;\n");
      out.write("            color: white;\n");
      out.write("            box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);\n");
      out.write("            transform: translateY(-1.5px);\n");
      out.write("        }\n");
      out.write("        .btn-action.delete {\n");
      out.write("            background: rgba(239, 68, 68, 0.1);\n");
      out.write("            color: #ef4444;\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.25);\n");
      out.write("        }\n");
      out.write("        .btn-action.delete:hover {\n");
      out.write("            background: #ef4444;\n");
      out.write("            color: white;\n");
      out.write("            box-shadow: 0 4px 12px rgba(239, 68, 68, 0.3);\n");
      out.write("            transform: translateY(-1.5px);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h2 class=\"page-title\">Individual Task Dashboard</h2>\n");
      out.write("\n");
      out.write("<div class=\"dashboard-grid\">\n");
      out.write("    <!-- Left Column: Controls & Task List -->\n");
      out.write("    <div class=\"dashboard-left\">\n");
      out.write("        <div class=\"dashboard-controls\">\n");
      out.write("            <a href=\"addTask.jsp\" class=\"btn-add\">Add Individual Task</a>\n");
      out.write("            <form method=\"get\" action=\"index.jsp\" class=\"search-form\">\n");
      out.write("                <input type=\"hidden\" name=\"page\" value=\"individual\">\n");
      out.write("                <input type=\"text\" name=\"search\" placeholder=\"Search tasks...\" value=\"");
      out.print( search != null ? search.replace("\"", "&quot;") : "" );
      out.write("\" />\n");
      out.write("                <select name=\"filter\">\n");
      out.write("                    <option value=\"Subject\" ");
      out.print( "Subject".equals(filter) ? "selected" : "" );
      out.write(">Subject</option>\n");
      out.write("                    <option value=\"Description\" ");
      out.print( "Description".equals(filter) ? "selected" : "" );
      out.write(">Description</option>\n");
      out.write("                    <option value=\"Status\" ");
      out.print( "Status".equals(filter) ? "selected" : "" );
      out.write(">Status</option>\n");
      out.write("                </select>\n");
      out.write("                <select name=\"sort\">\n");
      out.write("                    <option value=\"asc\" ");
      out.print( "asc".equals(sort) ? "selected" : "" );
      out.write(">Deadline Nearest</option>\n");
      out.write("                    <option value=\"desc\" ");
      out.print( "desc".equals(sort) ? "selected" : "" );
      out.write(">Deadline Farthest</option>\n");
      out.write("                </select>\n");
      out.write("                <button type=\"submit\" class=\"btn-search\">Search</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <table class=\"task-table\">\n");
      out.write("            <tr>\n");
      out.write("                <th style=\"width: 5%; text-align: center;\">ID</th>\n");
      out.write("                <th style=\"width: 20%;\">Subject</th>\n");
      out.write("                <th style=\"width: 30%;\">Description</th>\n");
      out.write("                <th style=\"width: 15%;\">Status</th>\n");
      out.write("                <th style=\"width: 10%;\">Start Date</th>\n");
      out.write("                <th style=\"width: 10%;\">Due Date</th>\n");
      out.write("                <th style=\"width: 10%; text-align: center;\">Action</th>\n");
      out.write("            </tr>\n");
      out.write("        ");

                while (rs.next()) {
                    String statusName = rs.getString(4);
        
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"text-align: center; color: rgba(255,255,255,0.4);\">");
      out.print( counter++ );
      out.write("</td>\n");
      out.write("                <td style=\"font-weight: 600;\">");
      out.print( rs.getString(2) );
      out.write("</td>\n");
      out.write("                <td style=\"color: rgba(255, 255, 255, 0.65);\">");
      out.print( rs.getString(3) );
      out.write("</td>\n");
      out.write("                <td><span class=\"status-label ");
      out.print( statusName.replace(" ", "") );
      out.write('"');
      out.write('>');
      out.print( statusName );
      out.write("</span></td>\n");
      out.write("                <td>");
      out.print( rs.getDate(5) );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( rs.getDate(6) );
      out.write("</td>\n");
      out.write("                <td style=\"text-align: center; white-space: nowrap;\">\n");
      out.write("                    <a href=\"editTask.jsp?id=");
      out.print( rs.getInt(1) );
      out.write("\" class=\"btn-action edit\">Edit</a>\n");
      out.write("                    <a href=\"deleteTask.jsp?id=");
      out.print( rs.getInt(1) );
      out.write("\" class=\"btn-action delete\" onclick=\"return confirm('Are you sure you want to delete this task?')\">Delete</a>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        ");

                }
            } catch (Exception e) {
                out.println("<tr><td colspan='7' style='text-align: center; padding: 30px; color: #ef4444;'>Error loading tasks: " + e.getMessage() + "</td></tr>");
                e.printStackTrace();
            } finally {
                if (rs != null) try { rs.close(); } catch (Exception ignored) {}
                if (stmt != null) try { stmt.close(); } catch (Exception ignored) {}
                if (conn != null) try { conn.close(); } catch (Exception ignored) {}
            }
        
      out.write("\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        ");
 if (counter == 1) { 
      out.write("\n");
      out.write("            <style>\n");
      out.write("                .task-table { display: none; }\n");
      out.write("                .empty-state-card {\n");
      out.write("                    background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("                    backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("                    -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("                    border: 2px dashed rgba(167, 139, 250, 0.25) !important;\n");
      out.write("                    border-radius: 20px;\n");
      out.write("                    padding: 50px 40px;\n");
      out.write("                    text-align: center;\n");
      out.write("                    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);\n");
      out.write("                    margin-top: 24px;\n");
      out.write("                    display: flex;\n");
      out.write("                    flex-direction: column;\n");
      out.write("                    align-items: center;\n");
      out.write("                    animation: fadeInUp 0.7s cubic-bezier(0.16, 1, 0.3, 1) both;\n");
      out.write("                }\n");
      out.write("                .empty-state-card h4 {\n");
      out.write("                    font-size: 18px;\n");
      out.write("                    color: #fff;\n");
      out.write("                    margin: 15px 0 8px 0;\n");
      out.write("                    font-weight: 700;\n");
      out.write("                    letter-spacing: -0.5px;\n");
      out.write("                }\n");
      out.write("                .empty-state-card p {\n");
      out.write("                    color: rgba(203, 213, 225, 0.55);\n");
      out.write("                    font-size: 14px;\n");
      out.write("                    max-width: 380px;\n");
      out.write("                    margin: 0 0 25px 0;\n");
      out.write("                    line-height: 1.6;\n");
      out.write("                }\n");
      out.write("            </style>\n");
      out.write("\n");
      out.write("            <div class=\"empty-state-card\">\n");
      out.write("                <!-- Glowing Sweeping Tech Radar SVG -->\n");
      out.write("                <svg viewBox=\"0 0 100 100\" width=\"85\" height=\"85\" style=\"margin-bottom: 10px; filter: drop-shadow(0 0 12px rgba(167,139,250,0.45));\">\n");
      out.write("                    <!-- Circular sweeps -->\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"45\" fill=\"none\" stroke=\"#8b5cf6\" stroke-width=\"1\" stroke-dasharray=\"6 4\" opacity=\"0.4\"/>\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"30\" fill=\"none\" stroke=\"#22d3ee\" stroke-width=\"0.8\" stroke-dasharray=\"10 5\" opacity=\"0.6\"/>\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"15\" fill=\"none\" stroke=\"#a78bfa\" stroke-width=\"0.8\" opacity=\"0.7\"/>\n");
      out.write("                    <!-- Radar crosshairs -->\n");
      out.write("                    <line x1=\"50\" y1=\"5\" x2=\"50\" y2=\"95\" stroke=\"#8b5cf6\" stroke-width=\"0.7\" opacity=\"0.3\" stroke-dasharray=\"4 4\"/>\n");
      out.write("                    <line x1=\"5\" y1=\"50\" x2=\"95\" y2=\"50\" stroke=\"#8b5cf6\" stroke-width=\"0.7\" opacity=\"0.3\" stroke-dasharray=\"4 4\"/>\n");
      out.write("                    <!-- Radar sweeping line -->\n");
      out.write("                    <line x1=\"50\" y1=\"50\" x2=\"78\" y2=\"22\" stroke=\"#22d3ee\" stroke-width=\"1.5\" stroke-linecap=\"round\">\n");
      out.write("                        <animateTransform attributeName=\"transform\" type=\"rotate\" from=\"0 50 50\" to=\"360 50 50\" dur=\"4s\" repeatCount=\"indefinite\"/>\n");
      out.write("                    </line>\n");
      out.write("                    <!-- Center glowing point -->\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"4\" fill=\"#a78bfa\">\n");
      out.write("                        <animate attributeName=\"opacity\" values=\"0.4;1;0.4\" dur=\"2s\" repeatCount=\"indefinite\"/>\n");
      out.write("                    </circle>\n");
      out.write("                </svg>\n");
      out.write("\n");
      out.write("                <h4>Radar Active: \"All Missions Completed!\"</h4>\n");
      out.write("                <p>No active individual tasks in your radar currently. Let's add a new task to begin your next productive journey!</p>\n");
      out.write("                <a href=\"addTask.jsp\" class=\"btn-add\">Add Individual Task</a>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Right Column: Progress & Quick Statistics -->\n");
      out.write("    <div class=\"dashboard-right\">\n");
      out.write("        <!-- Progress Summary -->\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("            <h3>Overall Progress</h3>\n");
      out.write("            ");

                int progressPercent = totalTasks > 0 ? (completed * 100 / totalTasks) : 0;
                String fillGradient = (progressPercent == 100) ? "linear-gradient(90deg, #10b981, #34d399)" : "linear-gradient(90deg, #8b5cf6, #3b82f6)";
                String glowShadow = (progressPercent == 100) ? "0 0 12px rgba(16, 185, 129, 0.4)" : "0 0 12px rgba(139, 92, 246, 0.4)";
            
      out.write("\n");
      out.write("            <div class=\"progress-bar\">\n");
      out.write("                <div class=\"progress-fill\" style=\"width: ");
      out.print( progressPercent );
      out.write("%; background: ");
      out.print( fillGradient );
      out.write("; box-shadow: ");
      out.print( glowShadow );
      out.write(";\"></div>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"progress-desc\"><strong>");
      out.print( completed );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( totalTasks );
      out.write("</strong> individual tasks completed (");
      out.print( progressPercent );
      out.write("%)</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Sidebar Stats Grid -->\n");
      out.write("        <div class=\"stats-sidebar-grid\">\n");
      out.write("            <div class=\"status-box pending\">\n");
      out.write("                <div class=\"status-icon\"><i class=\"bi bi-clock-history\"></i></div>\n");
      out.write("                <div class=\"status-details\">\n");
      out.write("                    <h3>");
      out.print( pending );
      out.write("</h3>\n");
      out.write("                    <p>Pending</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"status-box in-progress\">\n");
      out.write("                <div class=\"status-icon\"><i class=\"bi bi-play-circle\"></i></div>\n");
      out.write("                <div class=\"status-details\">\n");
      out.write("                    <h3>");
      out.print( inProgress );
      out.write("</h3>\n");
      out.write("                    <p>In Progress</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"status-box cancelled\">\n");
      out.write("                <div class=\"status-icon\"><i class=\"bi bi-x-circle\"></i></div>\n");
      out.write("                <div class=\"status-details\">\n");
      out.write("                    <h3>");
      out.print( cancelled );
      out.write("</h3>\n");
      out.write("                    <p>Cancelled</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"status-box completed\">\n");
      out.write("                <div class=\"status-icon\"><i class=\"bi bi-check-circle-fill\"></i></div>\n");
      out.write("                <div class=\"status-details\">\n");
      out.write("                    <h3>");
      out.print( completed );
      out.write("</h3>\n");
      out.write("                    <p>Completed</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
