/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-05-31 04:20:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/glowingTechElements.jsp", Long.valueOf(1780200909726L));
    _jspx_dependants.put("/DBConnection.jsp", Long.valueOf(1747368162000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Connection conn = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/task_manager", "root", "");
    } catch (Exception e) {
        out.println("Connection failed: " + e.getMessage());
    }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String message = "";

    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String username = request.getParameter("username");
        String password = request.getParameter("password");

        try {
            String sql = "SELECT * FROM user WHERE Username=? AND Password=?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, username);
            stmt.setString(2, password);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                session.setAttribute("username", rs.getString("Username"));
                session.setAttribute("userID", rs.getInt("User_ID"));
                response.sendRedirect("index.jsp");
                return;
            } else {
                message = "Invalid username or password.";
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            message = "Error: " + e.getMessage();
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Login - Task Manager</title>\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Outfit', sans-serif;\n");
      out.write("            background-color: #080614;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            overflow: hidden;\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Subtle Blueprint Tech Grid Background */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\";\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background-image: \n");
      out.write("                radial-gradient(rgba(255, 255, 255, 0.015) 1.5px, transparent 1.5px),\n");
      out.write("                linear-gradient(rgba(139, 92, 246, 0.008) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(139, 92, 246, 0.008) 1px, transparent 1px);\n");
      out.write("            background-size: 24px 24px, 48px 48px, 48px 48px;\n");
      out.write("            z-index: 1;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Extraordinary Floating Glow Orbs (Aurora Effect) */\n");
      out.write("        .bg-glow {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            z-index: 0;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1, .glow-2, .glow-3 {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(120px);\n");
      out.write("            opacity: 0.15;\n");
      out.write("            animation: float 25s infinite alternate ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1 {\n");
      out.write("            top: -15%;\n");
      out.write("            left: -10%;\n");
      out.write("            width: 50vw;\n");
      out.write("            height: 50vw;\n");
      out.write("            background: radial-gradient(circle, #8b5cf6 20%, transparent 70%);\n");
      out.write("            animation-duration: 20s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-2 {\n");
      out.write("            bottom: -20%;\n");
      out.write("            right: -10%;\n");
      out.write("            width: 55vw;\n");
      out.write("            height: 55vw;\n");
      out.write("            background: radial-gradient(circle, #3b82f6 20%, transparent 70%);\n");
      out.write("            animation-duration: 28s;\n");
      out.write("            animation-delay: -5s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-3 {\n");
      out.write("            top: 30%;\n");
      out.write("            left: 40%;\n");
      out.write("            width: 40vw;\n");
      out.write("            height: 40vw;\n");
      out.write("            background: radial-gradient(circle, #ec4899 10%, transparent 75%);\n");
      out.write("            animation-duration: 22s;\n");
      out.write("            animation-delay: -10s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0% {\n");
      out.write("                transform: translate(0, 0) scale(1) rotate(0deg);\n");
      out.write("            }\n");
      out.write("            50% {\n");
      out.write("                transform: translate(5vw, 6vh) scale(1.15) rotate(180deg);\n");
      out.write("            }\n");
      out.write("            100% {\n");
      out.write("                transform: translate(-3vw, -5vh) scale(0.9) rotate(360deg);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-wrapper {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            width: 90%;\n");
      out.write("            max-width: 400px;\n");
      out.write("            z-index: 10; /* Ensures content is above the glowing orbs */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .app-title {\n");
      out.write("            font-size: 38px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("            background: linear-gradient(135deg, #a78bfa, #c084fc, #818cf8);\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            text-align: center;\n");
      out.write("            letter-spacing: 2px;\n");
      out.write("            filter: drop-shadow(0 0 25px rgba(167, 139, 250, 0.35));\n");
      out.write("            margin-top: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container {\n");
      out.write("            background: rgba(20, 18, 43, 0.45) !important;\n");
      out.write("            backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            -webkit-backdrop-filter: blur(16px) saturate(120%) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            padding: 40px;\n");
      out.write("            border-radius: 24px;\n");
      out.write("            box-shadow: 0 30px 60px rgba(0, 0, 0, 0.4), \n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.1) !important;\n");
      out.write("            width: 100%;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            transition: transform 0.4s cubic-bezier(0.165, 0.84, 0.44, 1), \n");
      out.write("                        box-shadow 0.4s cubic-bezier(0.165, 0.84, 0.44, 1),\n");
      out.write("                        border-color 0.4s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 40px 80px rgba(139, 92, 246, 0.15),\n");
      out.write("                        inset 0 1px 0 rgba(255, 255, 255, 0.15) !important;\n");
      out.write("            border-color: rgba(167, 139, 250, 0.25) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 0;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("            color: #fff;\n");
      out.write("            font-weight: 700;\n");
      out.write("            font-size: 24px;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"text\"],\n");
      out.write("        input[type=\"password\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 14px 16px;\n");
      out.write("            margin: 8px 0 20px 0;\n");
      out.write("            background: #1c1a38;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            color: #fff;\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-family: inherit;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"text\"]::placeholder,\n");
      out.write("        input[type=\"password\"]::placeholder {\n");
      out.write("            color: rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input:focus {\n");
      out.write("            background: rgba(37, 34, 72, 0.6) !important;\n");
      out.write("            border-color: #a78bfa !important;\n");
      out.write("            outline: none;\n");
      out.write("            box-shadow: 0 0 18px rgba(167, 139, 250, 0.35) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            width: 100%;\n");
      out.write("            background: linear-gradient(135deg, #8b5cf6, #6366f1);\n");
      out.write("            color: white;\n");
      out.write("            padding: 14px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-family: inherit;\n");
      out.write("            cursor: pointer;\n");
      out.write("            box-shadow: 0 8px 24px rgba(139, 92, 246, 0.35);\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover {\n");
      out.write("            background: linear-gradient(135deg, #a78bfa, #818cf8);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 12px 30px rgba(139, 92, 246, 0.5);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:active {\n");
      out.write("            transform: translateY(0);\n");
      out.write("            box-shadow: 0 4px 15px rgba(139, 92, 246, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message {\n");
      out.write("            color: #fca5a5;\n");
      out.write("            background: rgba(239, 68, 68, 0.15);\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.25);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 15px;\n");
      out.write("            padding: 10px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.25);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .message:empty {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 25px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: rgba(255, 255, 255, 0.5);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a {\n");
      out.write("            color: #c084fc;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a:hover {\n");
      out.write("            color: #e9d5ff;\n");
      out.write("            text-shadow: 0 0 12px rgba(233, 213, 255, 0.4);\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Animated Glowing Orbs Background -->\n");
      out.write("    <div class=\"bg-glow\">\n");
      out.write("        <div class=\"glow-1\"></div>\n");
      out.write("        <div class=\"glow-2\"></div>\n");
      out.write("        <div class=\"glow-3\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Premium 3D Tech & Glass Elements -->\n");
      out.write("    ");
      out.write("<!-- Reusable Futuristic Glassmorphic & 3D Tech Elements Component -->\n");
      out.write("<style>\n");
      out.write("    /* Technical Abstract Animations */\n");
      out.write("    .tech-element-container {\n");
      out.write("        position: absolute;\n");
      out.write("        top: 0;\n");
      out.write("        left: 0;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        pointer-events: none;\n");
      out.write("        overflow: hidden;\n");
      out.write("        z-index: 2;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Floating Drifting Spheres */\n");
      out.write("    .glass-sphere {\n");
      out.write("        position: absolute;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        animation: sphereDrift 20s infinite alternate ease-in-out;\n");
      out.write("        opacity: 0.25;\n");
      out.write("        mix-blend-mode: plus-lighter;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .sphere-1 {\n");
      out.write("        top: 15%;\n");
      out.write("        right: 12%;\n");
      out.write("        width: 160px;\n");
      out.write("        height: 160px;\n");
      out.write("        animation-duration: 22s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sphere-2 {\n");
      out.write("        bottom: 15%;\n");
      out.write("        left: 10%;\n");
      out.write("        width: 200px;\n");
      out.write("        height: 200px;\n");
      out.write("        animation-duration: 28s;\n");
      out.write("        animation-delay: -5s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes sphereDrift {\n");
      out.write("        0% { transform: translate(0, 0) scale(1) rotate(0deg); }\n");
      out.write("        50% { transform: translate(25px, -30px) scale(1.08) rotate(180deg); }\n");
      out.write("        100% { transform: translate(-15px, 20px) scale(0.95) rotate(360deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Tech Rings Spinning in 3D */\n");
      out.write("    .tech-ring-container {\n");
      out.write("        position: absolute;\n");
      out.write("        width: 300px;\n");
      out.write("        height: 300px;\n");
      out.write("        opacity: 0.15;\n");
      out.write("        mix-blend-mode: screen;\n");
      out.write("        perspective: 1000px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .ring-left {\n");
      out.write("        bottom: 8%;\n");
      out.write("        left: 5%;\n");
      out.write("        animation: driftSlow 35s infinite alternate ease-in-out;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .ring-right {\n");
      out.write("        top: 8%;\n");
      out.write("        right: 5%;\n");
      out.write("        animation: driftSlow 30s infinite alternate ease-in-out -10s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes driftSlow {\n");
      out.write("        0% { transform: translate(0,0) rotate(0deg); }\n");
      out.write("        100% { transform: translate(30px, 40px) rotate(15deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .spinning-ring {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        transform-style: preserve-3d;\n");
      out.write("        animation: spinRing 25s infinite linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .spinning-ring-reverse {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        transform-style: preserve-3d;\n");
      out.write("        animation: spinRingRev 18s infinite linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes spinRing {\n");
      out.write("        from { transform: rotateX(65deg) rotateY(20deg) rotateZ(0deg); }\n");
      out.write("        to { transform: rotateX(65deg) rotateY(20deg) rotateZ(360deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes spinRingRev {\n");
      out.write("        from { transform: rotateX(55deg) rotateY(-25deg) rotateZ(360deg); }\n");
      out.write("        to { transform: rotateX(55deg) rotateY(-25deg) rotateZ(0deg); }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Ambient cyber particles */\n");
      out.write("    .ambient-particle {\n");
      out.write("        position: absolute;\n");
      out.write("        background: #a78bfa;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        opacity: 0;\n");
      out.write("        animation: twinkleParticle 4s infinite ease-in-out;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .particle-1 { top: 30%; left: 25%; width: 3px; height: 3px; animation-delay: 0.2s; }\n");
      out.write("    .particle-2 { top: 75%; left: 45%; width: 4px; height: 4px; animation-delay: 1.5s; background: #3b82f6; }\n");
      out.write("    .particle-3 { top: 20%; right: 30%; width: 3px; height: 3px; animation-delay: 2.8s; background: #ec4899; }\n");
      out.write("    .particle-4 { bottom: 30%; right: 20%; width: 4px; height: 4px; animation-delay: 0.9s; }\n");
      out.write("\n");
      out.write("    @keyframes twinkleParticle {\n");
      out.write("        0%, 100% { opacity: 0; transform: translateY(0) scale(0.8); }\n");
      out.write("        50% { opacity: 0.8; transform: translateY(-15px) scale(1.2); filter: drop-shadow(0 0 4px currentColor); }\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div class=\"tech-element-container\">\n");
      out.write("    <!-- Specular radial gradients inside SVGs for realistic 3D look -->\n");
      out.write("    <svg style=\"position: absolute; width: 0; height: 0;\">\n");
      out.write("        <defs>\n");
      out.write("            <radialGradient id=\"3dGlassGrad\" cx=\"35%\" cy=\"35%\" r=\"65%\">\n");
      out.write("                <stop offset=\"0%\" stop-color=\"#c084fc\" stop-opacity=\"0.6\"/>\n");
      out.write("                <stop offset=\"35%\" stop-color=\"#8b5cf6\" stop-opacity=\"0.3\"/>\n");
      out.write("                <stop offset=\"70%\" stop-color=\"#3b82f6\" stop-opacity=\"0.1\"/>\n");
      out.write("                <stop offset=\"95%\" stop-color=\"#080614\" stop-opacity=\"0.4\"/>\n");
      out.write("                <stop offset=\"100%\" stop-color=\"#8b5cf6\" stop-opacity=\"0.7\"/>\n");
      out.write("            </radialGradient>\n");
      out.write("            <linearGradient id=\"ringNeonGrad\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n");
      out.write("                <stop offset=\"0%\" stop-color=\"#a78bfa\"/>\n");
      out.write("                <stop offset=\"50%\" stop-color=\"#6366f1\"/>\n");
      out.write("                <stop offset=\"100%\" stop-color=\"#22d3ee\"/>\n");
      out.write("            </linearGradient>\n");
      out.write("        </defs>\n");
      out.write("    </svg>\n");
      out.write("\n");
      out.write("    <!-- 1. Floating Abstract Glass Spheres -->\n");
      out.write("    <!-- Sphere 1 (Top-Right) -->\n");
      out.write("    <div class=\"glass-sphere sphere-1\">\n");
      out.write("        <svg viewBox=\"0 0 100 100\" width=\"100%\" height=\"100%\">\n");
      out.write("            <circle cx=\"50\" cy=\"50\" r=\"48\" fill=\"url(#3dGlassGrad)\" stroke=\"rgba(255,255,255,0.15)\" stroke-width=\"0.5\"/>\n");
      out.write("            <!--Specularity -->\n");
      out.write("            <ellipse cx=\"38\" cy=\"38\" rx=\"12\" ry=\"6\" transform=\"rotate(-30 38 38)\" fill=\"white\" opacity=\"0.12\"/>\n");
      out.write("        </svg>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Sphere 2 (Bottom-Left) -->\n");
      out.write("    <div class=\"glass-sphere sphere-2\">\n");
      out.write("        <svg viewBox=\"0 0 100 100\" width=\"100%\" height=\"100%\">\n");
      out.write("            <circle cx=\"50\" cy=\"50\" r=\"48\" fill=\"url(#3dGlassGrad)\" stroke=\"rgba(255,255,255,0.15)\" stroke-width=\"0.5\"/>\n");
      out.write("            <ellipse cx=\"38\" cy=\"38\" rx=\"12\" ry=\"6\" transform=\"rotate(-30 38 38)\" fill=\"white\" opacity=\"0.12\"/>\n");
      out.write("        </svg>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 2. Cybernetic Neon Tech Rings (Perspectival spinning) -->\n");
      out.write("    <!-- Ring Left -->\n");
      out.write("    <div class=\"tech-ring-container ring-left\">\n");
      out.write("        <div class=\"spinning-ring\">\n");
      out.write("            <svg viewBox=\"0 0 200 200\" width=\"100%\" height=\"100%\">\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"90\" fill=\"none\" stroke=\"url(#ringNeonGrad)\" stroke-width=\"1.5\" stroke-dasharray=\"8 6\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"76\" fill=\"none\" stroke=\"#22d3ee\" stroke-width=\"0.8\" stroke-opacity=\"0.3\" stroke-dasharray=\"40 10 5 10\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"96\" fill=\"none\" stroke=\"#a78bfa\" stroke-width=\"0.5\" stroke-opacity=\"0.2\"/>\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Ring Right -->\n");
      out.write("    <div class=\"tech-ring-container ring-right\">\n");
      out.write("        <div class=\"spinning-ring-reverse\">\n");
      out.write("            <svg viewBox=\"0 0 200 200\" width=\"100%\" height=\"100%\">\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"90\" fill=\"none\" stroke=\"url(#ringNeonGrad)\" stroke-width=\"1.5\" stroke-dasharray=\"12 8\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"76\" fill=\"none\" stroke=\"#e879f9\" stroke-width=\"0.8\" stroke-opacity=\"0.3\" stroke-dasharray=\"25 15\"/>\n");
      out.write("                <circle cx=\"100\" cy=\"100\" r=\"96\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"0.5\" stroke-opacity=\"0.2\"/>\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 3. Twinkling Ambient Cyber Particles -->\n");
      out.write("    <div class=\"ambient-particle particle-1\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-2\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-3\"></div>\n");
      out.write("    <div class=\"ambient-particle particle-4\"></div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"login-wrapper\">\n");
      out.write("        <h1 class=\"app-title\">TASK MANAGER</h1>\n");
      out.write("        <div class=\"login-container\">\n");
      out.write("            <h2>Login</h2>\n");
      out.write("            <form method=\"post\">\n");
      out.write("                <input type=\"text\" name=\"username\" placeholder=\"Username\" required>\n");
      out.write("                <input type=\"password\" name=\"password\" placeholder=\"Password\" required>\n");
      out.write("                <button type=\"submit\">LOGIN</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div class=\"message\">");
      out.print( message );
      out.write("</div>\n");
      out.write("\n");
      out.write("            <div class=\"register-link\">\n");
      out.write("                Don't have an account? <a href=\"register.jsp\">Register</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
