/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-05-29 16:51:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.sql.*;

public final class memberManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/DBConnection.jsp", Long.valueOf(1747368162000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Connection conn = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/task_manager", "root", "");
    } catch (Exception e) {
        out.println("Connection failed: " + e.getMessage());
    }

      out.write('\n');
      out.write('\n');

    Integer userID = (Integer) session.getAttribute("userID");
    if (userID == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    String groupIdParam = request.getParameter("groupId");
    if (groupIdParam == null) {
        out.println("<p style='color:red;'>Group ID is missing!</p>");
        return;
    }

    int groupId = Integer.parseInt(groupIdParam);

    PreparedStatement checkStmt = null;
    ResultSet checkRs = null;

    try {
        String checkSql = "SELECT Role FROM group_members WHERE Group_ID = ? AND User_ID = ?";
        checkStmt = conn.prepareStatement(checkSql);
        checkStmt.setInt(1, groupId);
        checkStmt.setInt(2, userID);
        checkRs = checkStmt.executeQuery();

        if (!checkRs.next() || !"Leader".equals(checkRs.getString("Role"))) {
            out.println("<p style='color:red;'>Access denied. Only group leaders can manage members.</p>");
            return;
        }

        checkRs.close();
        checkStmt.close();

        String sql = "SELECT gm.User_ID, u.Username, gm.Role, g.Group_Name, gm.Group_ID, " +
             "t.Subject, t.Description, s.Name AS StatusName, t.Start_Date, t.Due_Date " +
             "FROM group_members gm " +
             "JOIN user u ON gm.User_ID = u.User_ID " +
             "JOIN `groups` g ON gm.Group_ID = g.Group_ID " +
             "JOIN tasks_group t ON gm.Group_ID = t.Group_ID " +
             "JOIN status s ON t.Status_ID = s.Status_ID " +
             "WHERE gm.Group_ID = ? AND gm.Role = 'Member'";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1, groupId);
        ResultSet rs = stmt.executeQuery();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Manage Group Members</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: 'Outfit', sans-serif;\n");
      out.write("            background-color: #080614;\n");
      out.write("            color: #e2e8f0;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            position: relative;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("            padding: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Subtle Blueprint Tech Grid Background */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\";\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background-image: \n");
      out.write("                radial-gradient(rgba(255, 255, 255, 0.015) 1.5px, transparent 1.5px),\n");
      out.write("                linear-gradient(rgba(139, 92, 246, 0.008) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(139, 92, 246, 0.008) 1px, transparent 1px);\n");
      out.write("            background-size: 24px 24px, 48px 48px, 48px 48px;\n");
      out.write("            z-index: 1;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animated Glowing Orbs Background */\n");
      out.write("        .bg-glow {\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            z-index: 0;\n");
      out.write("            overflow: hidden;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1, .glow-2, .glow-3 {\n");
      out.write("            position: absolute;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            filter: blur(140px);\n");
      out.write("            opacity: 0.15;\n");
      out.write("            animation: float 25s infinite alternate ease-in-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-1 {\n");
      out.write("            top: -10%;\n");
      out.write("            left: -10%;\n");
      out.write("            width: 45vw;\n");
      out.write("            height: 45vw;\n");
      out.write("            background: radial-gradient(circle, #8b5cf6 20%, transparent 70%);\n");
      out.write("            animation-duration: 22s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-2 {\n");
      out.write("            bottom: -15%;\n");
      out.write("            right: -5%;\n");
      out.write("            width: 50vw;\n");
      out.write("            height: 50vw;\n");
      out.write("            background: radial-gradient(circle, #3b82f6 20%, transparent 70%);\n");
      out.write("            animation-duration: 30s;\n");
      out.write("            animation-delay: -7s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glow-3 {\n");
      out.write("            top: 40%;\n");
      out.write("            left: 30%;\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 35vw;\n");
      out.write("            background: radial-gradient(circle, #ec4899 10%, transparent 75%);\n");
      out.write("            animation-duration: 25s;\n");
      out.write("            animation-delay: -12s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0% { transform: translate(0, 0) scale(1) rotate(0deg); }\n");
      out.write("            50% { transform: translate(4vw, 5vh) scale(1.1) rotate(180deg); }\n");
      out.write("            100% { transform: translate(-2vw, -4vh) scale(0.95) rotate(360deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container-fluid {\n");
      out.write("            z-index: 10;\n");
      out.write("            position: relative;\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-title {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            margin: 0;\n");
      out.write("            background: linear-gradient(135deg, #fff 40%, rgba(255, 255, 255, 0.7));\n");
      out.write("            -webkit-background-clip: text;\n");
      out.write("            -webkit-text-fill-color: transparent;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: rgba(255, 255, 255, 0.05) !important;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08) !important;\n");
      out.write("            color: white !important;\n");
      out.write("            font-weight: 600 !important;\n");
      out.write("            font-size: 14px !important;\n");
      out.write("            padding: 10px 18px !important;\n");
      out.write("            border-radius: 12px !important;\n");
      out.write("            transition: all 0.3s ease !important;\n");
      out.write("            display: inline-flex !important;\n");
      out.write("            align-items: center !important;\n");
      out.write("            gap: 8px !important;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.12) !important;\n");
      out.write("            border-color: rgba(255, 255, 255, 0.15) !important;\n");
      out.write("            transform: translateY(-1px) !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            margin-top: 1.5rem;\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: separate;\n");
      out.write("            border-spacing: 0;\n");
      out.write("            background: #14122b;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("            border-radius: 16px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);\n");
      out.write("        }\n");
      out.write("        th, td {\n");
      out.write("            padding: 16px 20px;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.06);\n");
      out.write("        }\n");
      out.write("        th {\n");
      out.write("            background: #1c1a38;\n");
      out.write("            color: #a5a1c9;\n");
      out.write("            font-weight: 700;\n");
      out.write("            font-size: 13px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("        }\n");
      out.write("        tr {\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        tr:hover td {\n");
      out.write("            background: rgba(255, 255, 255, 0.01);\n");
      out.write("        }\n");
      out.write("        tr:last-child td {\n");
      out.write("            border-bottom: none;\n");
      out.write("        }\n");
      out.write("        td {\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-action {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 6px 14px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 13px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            background: rgba(139, 92, 246, 0.1);\n");
      out.write("            color: #a78bfa;\n");
      out.write("            border: 1px solid rgba(139, 92, 246, 0.25);\n");
      out.write("        }\n");
      out.write("        .btn-action:hover {\n");
      out.write("            background: #8b5cf6;\n");
      out.write("            color: white;\n");
      out.write("            box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);\n");
      out.write("            transform: translateY(-1.5px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-badge {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            text-align: center;\n");
      out.write("            min-width: 90px;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("        .status-todo {\n");
      out.write("            background: rgba(245, 158, 11, 0.1) !important;\n");
      out.write("            color: #f59e0b !important;\n");
      out.write("            border: 1px solid rgba(245, 158, 11, 0.25) !important;\n");
      out.write("            box-shadow: 0 0 10px rgba(245, 158, 11, 0.1);\n");
      out.write("        }\n");
      out.write("        .status-inprogress {\n");
      out.write("            background: rgba(59, 130, 246, 0.1) !important;\n");
      out.write("            color: #3b82f6 !important;\n");
      out.write("            border: 1px solid rgba(59, 130, 246, 0.25) !important;\n");
      out.write("            box-shadow: 0 0 10px rgba(59, 130, 246, 0.1);\n");
      out.write("        }\n");
      out.write("        .status-done {\n");
      out.write("            background: rgba(16, 185, 129, 0.1) !important;\n");
      out.write("            color: #10b981 !important;\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.25) !important;\n");
      out.write("            box-shadow: 0 0 10px rgba(16, 185, 129, 0.1);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Animated Glowing Orbs Background -->\n");
      out.write("    <div class=\"bg-glow\">\n");
      out.write("        <div class=\"glow-1\"></div>\n");
      out.write("        <div class=\"glow-2\"></div>\n");
      out.write("        <div class=\"glow-3\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h2 class=\"page-title\">Manage Group Members</h2>\n");
      out.write("            <a href=\"index.jsp?page=group\" class=\"btn btn-secondary\">\n");
      out.write("                <i class=\"bi bi-arrow-left\"></i> Back to Group Tasks\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <th style=\"width: 5%; text-align: center;\">ID</th>\n");
      out.write("                <th style=\"width: 12%;\">Username</th>\n");
      out.write("                <th style=\"width: 10%;\">Role</th>\n");
      out.write("                <th style=\"width: 12%; text-align: center;\">Action</th>\n");
      out.write("                <th style=\"width: 12%;\">Group Name</th>\n");
      out.write("                <th style=\"width: 12%;\">Subject</th>\n");
      out.write("                <th style=\"width: 17%;\">Description</th>\n");
      out.write("                <th style=\"width: 10%;\">Status</th>\n");
      out.write("                <th style=\"width: 10%;\">Start Date</th>\n");
      out.write("                <th style=\"width: 10%;\">Due Date</th>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("    ");

            boolean hasMember = false;
            while (rs.next()) {
                hasMember = true;
    
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"text-align: center; color: rgba(255,255,255,0.4);\">");
      out.print( rs.getInt("User_ID") );
      out.write("</td>\n");
      out.write("                <td style=\"font-weight: 600;\">");
      out.print( rs.getString("Username") );
      out.write("</td>\n");
      out.write("                <td style=\"color: #c084fc;\">");
      out.print( rs.getString("Role") );
      out.write("</td>\n");
      out.write("                <td style=\"text-align: center;\">\n");
      out.write("                    <!-- Edit Task Form -->\n");
      out.write("                    <form action=\"editGroupTask.jsp\" method=\"get\" style=\"display:inline-block; margin: 0;\">\n");
      out.write("                        <input type=\"hidden\" name=\"groupId\" value=\"");
      out.print( rs.getInt("Group_ID") );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"subject\" value=\"");
      out.print( rs.getString("Subject") );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"description\" value=\"");
      out.print( rs.getString("Description") );
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"status\" value=\"");
      out.print( rs.getString("StatusName") );
      out.write("\">\n");
      out.write("                        <button type=\"submit\" class=\"btn-action\">Edit Task</button>\n");
      out.write("                    </form>\n");
      out.write("                </td>\n");
      out.write("                <td style=\"font-weight: 500;\">");
      out.print( rs.getString("Group_Name") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( rs.getString("Subject") );
      out.write("</td>\n");
      out.write("                <td style=\"color: rgba(255, 255, 255, 0.65);\">");
      out.print( rs.getString("Description") );
      out.write("</td>\n");
      out.write("                <td>\n");
      out.write("                    ");

                        String status = rs.getString("StatusName");
                        String statusClass = "status-badge ";
                        if ("To Do".equalsIgnoreCase(status) || "Pending".equalsIgnoreCase(status)) {
                            statusClass += "status-todo";
                        } else if ("In Progress".equalsIgnoreCase(status)) {
                            statusClass += "status-inprogress";
                        } else if ("Done".equalsIgnoreCase(status) || "Completed".equalsIgnoreCase(status)) {
                            statusClass += "status-done";
                        } else {
                            statusClass += "status-todo"; 
                        }
                    
      out.write("\n");
      out.write("                    <span class=\"");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( status );
      out.write("</span>\n");
      out.write("                </td>\n");
      out.write("\n");
      out.write("                <td>");
      out.print( rs.getDate("Start_Date") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( rs.getDate("Due_Date") );
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("    ");

            }

            if (!hasMember) {
    
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td colspan=\"10\" style=\"text-align: center; padding: 30px; color: rgba(255, 255, 255, 0.45);\">No members found in this group.</td>\n");
      out.write("            </tr>\n");
      out.write("    ");

            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            out.println("<tr><td colspan='10' style='text-align: center; padding: 30px; color: #ef4444;'>Error loading tasks: " + e.getMessage() + "</td></tr>");
            e.printStackTrace();
        }
    
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
